# Generated by Django 5.0.3 on 2024-09-03 06:43

import location_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True, validators=[location_app.validators.validate_location])),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, validators=[location_app.validators.validate_email])),
                ('phone_number', models.CharField(max_length=15, validators=[location_app.validators.validate_phone_number])),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
