# Generated by Django 5.0.3 on 2024-09-04 15:43

import django.db.models.deletion
import location_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[location_app.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[location_app.validators.validate_phone_number]),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='location_app.locationdetails')),
            ],
        ),
    ]
