# Generated by Django 5.0.3 on 2024-09-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_alter_locationdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('locations', models.ManyToManyField(related_name='doctors', to='location_app.locationdetails')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='location_app.speciality')),
            ],
        ),
    ]
